title = "Nick Kirkes"
baseURL = "https://nkirkes.github.io"
languageCode = "en-us"
theme = 'ananke'

SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Drive fast. Take chances."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/nickkirkes"