baseURL: "https://nkirkes.github.io"
title: 'Silicorn Valley'
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: 'Silicorn Valley'
  description: 'Personal writings of Nick Kirkes, a technical professional born in California, self-taught in Colorado, and leveled up in Indiana. Currently based in North Carolina.'
  keywords: [Blog, Portfolio, Technology, Software Development, Startups, Engineering Leadership]
  author: 'Nick Kirkes'
  images: [silicorn.png]
  #DateFormat: 'January 2, 2006'
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    #favicon: "<link / abs url>"
    #favicon16x16: "<link / abs url>"
    #favicon32x32: "<link / abs url>"
    #apple_touch_icon: "<link / abs url>"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: 'Silicorn Valley'
    icon: /silicorn.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hey! \U0001F44B"
    Content: I'm Nick Kirkes, and this is my blog, Silicorn Valley. I'm a long-time software engineering leader, currently with the fantastic teams at Zoom. I'm new to public writing, but I hope to offer something useful, if not entertaining. Thanks for reading!

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/nickkirkes'
    - name: linkedin
      url: 'https://www.linkedin.com/in/nickkirkes'
    - name: kofi
      url: 'https://ko-fi.com/nickkirkes'
    #- name: github
    #  url: 'https://github.com/nkirkes'
    #- name: stackoverflow
    #  url: "https://stackoverflow.com"
    

  #analytics:
  #  google:
  #    SiteVerificationTag: "XYZabc"
  #  bing:
  #    SiteVerificationTag: "XYZabc"
  #  yandex:
  #    SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    #- identifier: categories
    #  name: categories
    #  url: /categories/
    #  weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai